export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST';
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD';
export const BLOG_POST_LIST_RECEIVE = 'BLOG_POST_LIST_RECEIVE';
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR';

export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST';
export const BLOG_POST_ADD = 'BLOG_POST_ADD';
export const BLOG_POST_RECEIVE = 'BLOG_POST_RECEIVE';
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR';
